  <postalcode>           ::= <forwardsortationarea> <space> <localdeliveryunit>
  <forwardsortationarea> ::= <provarea> <loctype> <letter>
  <localdeliveryunit>    ::= <digit> <letter> <digit>
  <loctype>              ::= <rural> | <urban>
  <rural>                ::= "0"
  <urban>                ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
 <letter>         ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
 <provarea>         ::= "A" | "B" | "C" | "D" | "E" | "G" | "H" | "J" | "K" | "L" | "M" | "N" | "P" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y"
 <digit>          ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
 <space> ::= " "
